/website
    /css
        style.css
    /images
        GEAVlogo2b.png
        N251MB-prop.jpg
        N251MB-1.jpg
        N251MB-2.jpg
        N251MB-3.jpg
    /js
        script.js
    index.html
    about.html
    partnership.html
    aircraft.html
    gallery.html
    contact.html